### ISSUE TITLE
question about your blog post

### ISSUE THREAD

**Issue by zemora** [jpivarski/hyperbolic-storage-space#2]
Hi Jim, thanks for this helpful project and your nice post here:
http://coffeeshopphysics.com/articles/2012-12/22_lost_in_hyperbolia/
I'm wondering how you rendered the first image in the blog post above:
![splash400](https://user-images.githubusercontent.com/23551786/73282162-0f3ef580-422c-11ea-9c8d-bb53c90efcbe.jpg)
any possile chance for sharing the source?
thanks!

**Comment by jpivarski** [comment]
I almost certainly used [The Gimp](https://www.gimp.org/), but I'm sure I wouldn't be able to find the sources now, 8 years later.

They're both Escher works—the leaf with a big water droplet on it was originally all grayscale with no hyperbolic tiling inside. I probably scaled them both up, aligned the hyperbolic tiling layer as well as I could over the leaf (temporarily setting the upper layer to 50% transparency so that I could improve the alignment by seeing through it), and then maybe used iWarp to adjust for the water droplet's non-sphericity. At least, that's how I would do it now.

**Comment by zemora** [comment]
Got that. I'm considering using Escher's image as texture in a POV-Ray scene, that's way I'm interested in your image. Anyway your work is impressvie. Thanks for your reply.

**Comment by jpivarski** [comment]
Not that I did this correctly either, but Escher's works might not be out of copyright. So depending on what you'll be using it for, that might matter.

(Closed accidentally, but this thread can be closed, anyway.)
